#+setupfile: ../../../.org-templates/level/1.org
#+title: Regular Expressions Tutorial
#+description: In this tutorial, I'll walk you through the most practical aspects of regular expressions and their use in JavaScript.
* Introduction
A Regular Expression (I'll often call it a regex for short) is a sequence of characters that define a search pattern. It provides you with the syntax to very specifically match characters in a given string. And, it makes you look cool on [[https://www.codewars.com/users/thewebmasterp][Codewars]] with those one-liner solutions 😃.

Let's get our hands dirty right away with an example!
#+begin_src js -n
  const regex = /[A-Z]\w+/g;
#+end_src
+ ~/.../g~ - Just like the content of an array literal is enclosed between ~[]~, a regular expression literal consists of a pattern enclosed between slashes ~//~. ~g~ is called a flag, more on that later.
+ ~[A-Z]~ - Matches uppercase letters from A to Z
+ ~\w~ is a shorthand for ~[A-Za-z0-9_]~ (uppercase letters from A to Z, lowercase letters from a to z, numerals from 0 to 9, underscore)
+ ~+~ One or more instances of the preceding element (~\w~)
#+begin_src js -n
  const str = 'Nikola, Georgi and Viktoria are all coders who live in Bulgaria'

  console.log( str.match(regex) )
  // => [ "Nikola", "Georgi", "Viktoria", "Bulgaria" ]
#+end_src
This operation can be performed using vanilla JavaScript but regular expressions are the better tool for that. You don't use a hammer to fasten some papers with a staple, do you?
* Creating Regular Expressions
A regular expression can be created using a literal:
#+begin_src js -n
  const regex = /[A-Z]\w+/g;
  // The content between /.../ is the actual regex.
  // The letter after the last slash is called a flag.
  // You can have multiple flags.
#+end_src
Or by calling the constructor function of the RegExp object:
#+begin_src js -n
  const regex = new RegExp('[A-Z]\w+', 'g');
  // First parameter is the actual regex, in a string.
  // Second parameter is a string containing flags.
#+end_src
Most of the time, you'd prefer using the literal expression as it is as well as with arrays  - you prefer ~[1, 2]~, rather than ~Array(1, 2)~. The constructor way of initializing a regular expression is useful when you want to pass the regex as a string, which is powerful. Your program can generate the string based on its state and on top of regex's power, this makes you invincible ⚡. Let's keep on rocking!
* The very basics
Let's try to match the word "apple". ~/apple/~ would do the job. It, however, won't match "APPLE" or "aPpLe", because regex is case sensitive.

To disable case sensitivity in regex use what's called an ~i~ flag, like this ~/apple/i~. Now it will match "apple", "APPLE" & "aPpLe"

If you want to match two words in a single regex, use ~/apple|nut/~.
** Usage in JavaScript
Take this as an introduction to the most basic methods in JS for working with regexes.
*** str.match(regex)
returns an array with all the matches. However, there's a little catch here. If you try doing this:
#+begin_src js -n
  "apple apple".match(/apple/)
#+end_src
you'd probably expect to get ~[ 'apple', 'apple' ]~ but that's not the case. Without its ~g~ flag, regex won't match multiple occurrences. So in that case, ~/apple/~ matches just the first occurrence of the substring "apple" and ~/apple/g~ matches all of the occurrences. 
*** regex.test(str)
Think of ~regex~ as a variable holding a RegExp object and ~str~ is the string you test against ~regex~. The method returns a boolean indicating whether it matched or not.

Let's play with all we've just learned:
#+begin_src js -n
  let regex = /code|easy/i
  const str = "this code is EaSy super easy"
  regex.test(str) // => true; we've got a match!

  str.match(regex) // => [ "code", index: 5, input... ]

  // Oops! We forgot adding the g flag
  regex = /code|easy/ig

  str.match(regex) // => [ "code", "EaSy", "easy" ]
  // Alright!
#+end_src
* Flags
Flags are like settings to your regular expression that help you control its behavior. They're placed after the last slash of a regex literal or in a string as a second parameter of the RegExp constructor.

In JavaScript, we have 6 flags that affect the match
+ ~i~
  Makes the match case-insensitive, i.e. make no difference between "C" and "c".
+ ~g~
  Without this flag only the first match will be returned.
+ ~m~
  Multiline mode; only affects the behavior of ~^~ and ~$~ (more on these, later).
+ ~s~
  Dotall mode; Allows wildcard period ~.~ to match newline character ~\n~.
+ ~u~
  Enables full unicode support.
+ ~y~
  Sticky mode. Enables searching at a specific position.
* Match anything with wildcard period
Now that we've covered the very basics, let the real fun begin!

We've learned how to statically match a word like ~/hug/~. Now what if we want to match "hu​_h_", "hu​_b_", "hu​_g_", "hu​_m_" all with the same regular expression? Wildcard on help!
#+begin_src js -n
  /hu./
#+end_src
The above regular expression will match "hu<any character here>"
* Match a single character with multiple possibilities
The Wildcard period is way too loose in most cases and you need to match only a specific set of characters. That's when you need the ~[]~ construct to do something like this:
#+begin_src js -n
  /hu[hb]/
#+end_src
Which will match "hu​_h_", "hu​_b_" but not "hu​_g_" or "hu​_m_".
** More complex cases
#+begin_src js -n
  "abcdefghijklmnopqr".match(/[defghij]/g)
  // => [ "d", "e", "f", "g", "h", "i", "j" ]

  // Same as
  
  "abcdefghijklmnopqr".match(/[d-j]/g)
  // => [ "d", "e", "f", "g", "h", "i", "j" ]
#+end_src

  And

#+begin_src js -n
  "1234567890".match(/[456789]/g)
  // => [ "4", "5", "6", "7", "8", "9" ]

  // Same as

  "1234567890".match(/[4-9]/g)
  // => [ "4", "5", "6", "7", "8", "9" ]
#+end_src

You can also combine multiple rules like ~[A-Za-z0-9_]~.
** Common shorthands
+ Instead of ~[A-Za-z0-9]~, simply use ~\w~.
+ Instead of ~[^A-Za-z0-9]~, simply use ~\w~.
+ Instead of ~[0-9]~, simply use ~\d~.
+ Instead of ~[^0-9]~, simply use ~\D~.
+ Instead of ~[\r\t\f\n\v]~ (matches all kinds of whitespaces), simply use ~\s~.
+ Instead of ~[^\r\t\f\n\v]~, simply use ~\​S~.
** Reverse the character classes
~[a-z]~ will match all letters from a to z. To invert this selection and match all symbols *except* the ones specified, use ~[^a-z]~. Note that ~^~ character has a completely different behavior used outside of ~[]~.
* Match characters that occur one or more times
With the ~+~ character that matches one or more instances of the preceding element. Best show you an example:
 #+begin_src js -n
  const regex = /a+/g
  "abc".match(regex)    // => [ 'a' ]
  "aabc".match(regex)   // => [ 'aa' ]
  "aabac".match(regex) // => [ 'aa', 'a' ]
  "bbc".match(regex)    // => null

  const regex = /a/g
  "abc".match(regex)    // => [ 'a' ]
  "aabc".match(regex)   // => [ 'a', 'a' ]
  "aabac".match(regex) // => [ 'a', 'a', 'a' ]
  "bbc".match(regex)    // => null
#+end_src
* Look for patterns from the beginning or from the end of string
To search for a character from the beginning of a string, use ~^~.
#+begin_src js -n
  const regex = /^K/
  regex.test("__K_K_") // => false: K is not exactly in the beginning
  regex.test("K__K__") // => true: K is in the beginning
#+end_src

To search for a character from the end of a string, use ~$~.
#+begin_src js -n
  const regex = /K$/
  regex.test("__K_K_") // => false: K is not exactly in the end
  regex.test("__K") // => true: K is in the end
#+end_src
* Optional Character
#+begin_src js -n
  const regex = /colou?r/ // Makes "u" optional

  const american = "color"
  const british = "colour"

  regex.test(american) // => true
  regex.test(british)  // => true
  regex.test("cologr") // => false
#+end_src
* Specify upper and lower limit of matches
What if you want to match a sequence of characters that repeats X times? ~/a{5}/~ would do the trick!
#+begin_src js -n
  const str = "ama baalo maaaaamal aaaaa"
  console.log( str.match( /a{5}/g ) ) // => [ "aaaaa", "aaaaa" ]
#+end_src
To match "m" letter followed by 5 times "a": ~/ma{5}/~. To match an empty space followed by 4 times "a": ~/\sa{4}/~.

Now, what if you want to match from *m* to *p* repeating characters? ~/a{1,3}/~ applied to ~str~ (from the last example) would match "a", "aa" and "aaa". If any of *m* or *p* needs to be infinity (/[1, ∞]/ or /[∞, 3]/) we can omit an argument, respectively like ~/a{1,}/~ or ~/a{,3}/~.
* Match characters that occur multiple times
** Match *one or more* characters
~+~ after the target character
#+begin_src js -n
  const str = "ama baalo maaaaamal"

  console.log( str.match( /a+/g ) )
  // => ["a", "a", "aa", "aaaaa", "a"]

  console.log( str.match( /a/g ) )
  // => [ "a", "a", "a", "a", "a", "a", "a", "a", "a", "a" ]
#+end_src
** Match *zero or more* characters
~*~ after the target character
#+begin_src js -n
  const str = "aaa"

  console.log( str.match( /a*/g ) )
  // => ["aaa", ""]

  console.log( str.match( /a/g ) )
  // => ["a", "a", "a"]
#+end_src
** Match *zero or one* character
~?~ after the target character
#+begin_src js -n
  const str = "aaa"
  console.log( str.match( /a?/g ) )
  // => ["a", "a", "a", ""]
#+end_src
* Positive and negative lookahead
This is considered to be one of the abstract topics in regex, but I will try to cover 80/100 of what you need to know.

 + ~a(?=g)~ - Positive LookAhead. Matches all "a" that are *followed* by "g", without making the "g" part of the match.

 + ~a(?!g)~ - Negative LookAhead. Matches all "a" that are *not followed* by "g", without making "g" part of the match.

Positive/Negative LookAhead is a powerful feature. consider this: ~(?=regex)~ or ~(?!regex)~. You can replace regex with any valid regular expression!

Let's play with it a little;
#+begin_src js -n
  const str = "IsFunBaloonIsLearningRegExIsLean"

  // Matches the 2nd "Is", right before "Learning"
  console.log( str.match( /Is(?=Learning)/ ) )
  // => [ "Is", index: 11, ... ]

  // Matches the 3rd "Is", right before "Lean"
  console.log( str.match( /Is(?=Lean)/ ) )
  // => [ "Is", index: 26, ... ]

  // Matches all "Is" that are followed by "L"
  console.log( str.match( /Is(?=L)/g ) )
  // => [ "Is", "Is" ]

  // Match all "Is" that aren't followed by "L"
  console.log( str.match( /Is(?!L)/ ) )
  // => [ "Is", index: 0, ... ]
#+end_src
* Reusing patterns with *Capture Groups*
We all know and should obey the DRY principle. Capture groups help us do exactly this. No better way to explain it than a few good examples:
** First example
~/(bamm+)\w\1/g~ same as

~/(bamm+)\w(bamm+)/g~ same as

~/bamm+\wbamm+/g~
** Second example
~/(\w+)\s(\1\1\1)\2/g~ same as

~/(\w+)\s\1\1\1\1\1\1/g~
** Third example
~/(\w+)\s\1\1\1/g~ same as

~/\w+\s\w+\w+\w+/g~
* All 8 JavaScript methods which use regex
** *str*.match(*regex*)
Finds all matches of *regex* in the string *str* and returns an array of those matches.
** *regex*.exec(*str*)
Similar to the ~.match()~ method but it's meant to be used in a loop when the *regex* is stored in a global variable but not passed directly.
#+begin_src js -n
  let re = /bla/g
  let str = 'bla and yeah bla yeh'

  re.exec(str) // => ["bla", index: 0, ...]
  re.exec(str) // => ["bla", index: 13, ...]
  re.exec(str) // => null
  re.exec(str) // => ["bla", index: 0, ...]: Starts again.
#+end_src
Usage with a loop:
#+begin_src js -n
  let match, str = 'bla and yeah bla yeh ble'
  while (match = re.exec(str)) {
    console.log(match)
  }
  // => ["bla", index: 0, input: ...]
  // => ["bla", index: 13, input: ...]
#+end_src
~.match()~ compared to ~.exec()~ is pretty simple:
#+begin_src js -n
  str.match(re)
  // => ["bla", "bla"]
#+end_src
** *str*.matchAll(*regex*)
An improvement over the previously covered ~.match()~ method, ~matchAll()~ was introduced in ES2020

~.matchAll()~ is introduced in ES2020 and it is an improvement on the ~.match()~ method. There are three differences between the two:
1. ~.matchAll()~ returns an iterable object with matches instead of an array.
2. Each match is in the same format as ~str.match()~ without the 'g' flag.
3. If there are no matches, it returns an empty iterable object, rather than null if you used ~.match()~
I think this method is most usable when a 'g' flag is added to the *regex*.
#+begin_src js -n
  let regexp = /bla/g
  let str = 'bla and yeah bla yeh'
  const matches = str.matchAll(regexp)
  for (let match of matches) {
    console.log(match)
  }
  // => ["bla", index: 0, ...]
  // => ["bla", index: 13, ...]
#+end_src
** *regex*.test(*str*)
Looks for at least one match of *regex* in *str*. If found, returns true. Otherwise, false.
** *str*.search(*regex*)
Returns the index of the first available match. If no match is found, it returns -1.
** *str*.split(*separator*)
Instead of passing a simple string to *separator* like '' (in the most frequent case), we can also pass regex for more precise split.
** *str*.replace(*from*, to)
*from* is what to match. It can be a string or regex. The first match will be replaced with the string you have passed to the *to* argument. Instead of a string, you can pass a function too.

If you add a 'g' flag to the regex, ~.replace()~ starts working like the next and final method: 
** *str*.replaceAll(*from*, to)
Same as ~.replace()~, except that instead of replacing only the first match, it will replace all matches with the provided *to*.

A comparison between the last two:
#+begin_src js -n
  let str = "stuffed str living fforever pff"
  let regex = /f+/ // Match one or more 'f'

  str.replace(regex, '*') // => 'stu*ed str living fforever pff'
  str.replaceAll(regex, '*') // => 'stu*ed str living *orever p*'
#+end_src
* Closing words
Congratulations! Now you have the understanding to start using regular expressions in your practice.

This article is an improved version of the ones I wrote in 2020:
#+BEGIN_EXPORT html
<div class="list-insta-posts">
<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/CDEX5vkg5Ym/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CDEX5vkg5Ym/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CDEX5vkg5Ym/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by webmaster_project | JavaScript (@webmaster_project)</a></p></div></blockquote>

<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/CDWZySuADok/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CDWZySuADok/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CDWZySuADok/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by webmaster_project | JavaScript (@webmaster_project)</a></p></div></blockquote>

<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/CDjOxFTAKM_/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/CDjOxFTAKM_/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/CDjOxFTAKM_/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by webmaster_project | JavaScript (@webmaster_project)</a></p></div></blockquote>
<script async src="//www.instagram.com/embed.js"></script>
</div>
#+END_EXPORT

Please, ask your questions and leave your suggestions down in the comments. They'll help me understand where my explanation is lacking and therefore improve it. Know that this is a dynamic article: One changing over time in dependence on the feedback I get. Let us together make this the best introduction to regular expressions available on the web!

** Contributors
:PROPERTIES:
:CUSTOM_ID: contributors_table
:END:
No contribution is left unnoticed. The people who helped this article evolve into what it is today are listed here:
+ thewebmasterp

